version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    # command:  php artisan serve --host=0.0.0.0 --port=8000
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - laravel_network
    links:
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_HOST=mysql
      - REDIS_HOST=redis
      - REDIS_PASSWORD
      - REDIS_PORT
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - LOG_CHANNEL
      - LOG_LEVEL
      - DB_CONNECTION
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - BROADCAST_DRIVER
      - FILESYSTEM_DRIVER
      - SESSION_LIFETIME
      - mMEMCACHED_HOST
      - MAIL_MAILER
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_USERNAME
      - MAIL_PASSWORD
      - MAIL_ENCRYPTION
      - MAIL_FROM_ADDRESS
      - MAIL_FROM_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_BUCKET
      - AWS_USE_PATH_STYLE_ENDPOINT
      - PUSHER_APP_ID
      - PUSHER_APP_KEY
      - PUSHER_APP_SECRET
      - PUSHER_APP_CLUSTER
      - MIX_PUSHER_APP_KEY
      - MIX_PUSHER_APP_CLUSTER
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
