version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: voyace-app
    container_name: voyace-app
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env  # Référence à votre fichier .env
    environment:
        APP_ENV:
        APP_DEBUG:
        APP_KEY:
        DB_HOST:
        REDIS_HOST: redis
        REDIS_PASSWORD:
        REDIS_PORT:
        CACHE_DRIVER: redis
        SESSION_DRIVER: redis
        QUEUE_CONNECTION: redis
        LOG_CHANNEL:
        LOG_LEVEL:
        DB_CONNECTION:
        DB_PORT:
        DB_DATABASE:
        DB_USERNAME:
        DB_PASSWORD:
        BROADCAST_DRIVER:
        FILESYSTEM_DRIVER:
        SESSION_LIFETIME:
        mMEMCACHED_HOST:
        MAIL_MAILER:
        MAIL_HOST:
        MAIL_PORT:
        MAIL_USERNAME:
        MAIL_PASSWORD:
        MAIL_ENCRYPTION:
        MAIL_FROM_ADDRESS:
        MAIL_FROM_NAME:
        AWS_ACCESS_KEY_ID:
        AWS_SECRET_ACCESS_KEY:
        AWS_DEFAULT_REGION:
        AWS_BUCKET:
        AWS_USE_PATH_STYLE_ENDPOINT:
        PUSHER_APP_ID:
        PUSHER_APP_KEY:
        PUSHER_APP_SECRET:
        PUSHER_APP_CLUSTER:
        MIX_PUSHER_APP_KEY:
        MIX_PUSHER_APP_CLUSTER:

    volumes:
      - .:/var/www/html

